apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge
spec:
  selector:
    matchLabels:
      app: devops-challenge
  template:
    metadata:
      labels:
        app: devops-challenge
    spec:
      containers:
      - name: devops-challenge
        image: devtraining/sample-web-app:1
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        ports:
            - name: http
              containerPort: 8080
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: devops-challenge-app-service
  labels:
    app: devops-challenge
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: devops-challenge
